source 'https://cdn.cocoapods.org/'
source 'git@bitbucket.org:ioasys/ioasys-specs.git'

platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!
workspace 'teste-ioasys'

def uiPods
  pod 'SnapKit', '~> 5.0'
  pod 'Material', '~> 2.16.4'
  pod 'SDWebImage', '~> 5.11'
#  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON', '~> 5.0'
end

target 'teste-ioasys' do
  project 'teste-ioasys'
  
  uiPods
  
  target 'teste-ioasysTests' do
    inherit! :search_paths
  end

  target 'teste-ioasysUITests' do
    # Pods for testing
  end
end
