platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!
workspace 'teste-ioasys'

def sharedPods
  pod 'SwiftLint'
end

def diPods
  pod 'Swinject', '~> 2.7.1'
  pod 'SwinjectAutoregistration', '~> 2.7.0'
end

target 'teste-ioasys' do
  project 'teste-ioasys'
  
  sharedPods
  diPods
  
  pod 'SnapKit', '~> 5.0'
  pod 'Material', '~> 2.16.4'
  pod 'Alamofire', '~> 5.4.1'
  pod 'SwiftyJSON', '~> 5.0'
#  pod 'KeychainSwift', '~> 11.0.0'
  pod 'SDWebImage', '~> 5.11'
  pod 'Swinject', '~> 2.7.1'
  pod 'SwinjectAutoregistration', '~> 2.7.0'

  target 'teste-ioasysTests' do
    inherit! :search_paths
  end

  target 'teste-ioasysUITests' do
    # Pods for testing
  end
end

target 'Domain' do
  project 'Domain/Domain'

  sharedPods

  target 'DomainTests'
end
