# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'teste-ioasys' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for teste-ioasys

  pod 'SnapKit', '~> 5.0'
  pod 'Material', '~> 2.16.4'
  pod 'Alamofire', '~> 5.4.1'
  pod 'SwiftyJSON', '~> 5.0'
#  pod 'KeychainSwift', '~> 11.0.0'
  pod 'SDWebImage', '~> 5.11'

  target 'teste-ioasysTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'teste-ioasysUITests' do
    # Pods for testing
  end

end
